//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Users
    {
        public long UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string ProjectName { get; set; }
        public string TaskName { get; set; }
    }
}
